// Auto-generated version file - DO NOT EDIT MANUALLY
#ifndef VERSION_H
#define VERSION_H

#define FIRMWARE_VERSION "1.0.9"
#define FIRMWARE_VERSION_MAJOR 1
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 9
#define BUILD_DATE "2026-01-28"
#define BUILD_TIME "21:29:46"
#define BUILD_TIMESTAMP "2026-01-28 21:29:46"

#endif // VERSION_H
