// Auto-generated version file - DO NOT EDIT MANUALLY
#ifndef VERSION_H
#define VERSION_H

#define FIRMWARE_VERSION "1.0.2"
#define FIRMWARE_VERSION_MAJOR 1
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 2
#define BUILD_DATE "2026-01-28"
#define BUILD_TIME "20:04:28"
#define BUILD_TIMESTAMP "2026-01-28 20:04:28"

#endif // VERSION_H
